add failed phase

diff --git a/pod-lifecycle/manifests/failed.yaml b/pod-lifecycle/manifests/failed.yaml
--- a/pod-lifecycle/manifests/failed.yaml
+++ b/pod-lifecycle/manifests/failed.yaml
@@ -1,7 +1,7 @@
 apiVersion: v1
 kind: Pod
 metadata:
-  name: succeeded-pod
+  name: failed-pod
 spec:
   restartPolicy: Never
   containers:
@@ -17,4 +17,4 @@ spec:
     command: ["sh", "-c"]
     args:
     - |
-      echo "This is succeeded phase"; exit 0
+      echo "This is failed phase"; exit 1
